name: Build and Release Purpur Plugin

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Даем процессу права на создание релизов и загрузку файлов
    permissions:
      contents: write

    steps:
    # 1. Скачиваем код из твоего репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Устанавливаем Java 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    # 3. Компилируем плагин через Мавен
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    # 4. Автоматически создаем Релиз и загружаем туда готовый .jar
    - name: Create Release and Upload Jar
      uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_number }} # Каждая сборка получит уникальный номер
        name: "Авто-сборка #${{ github.run_number }}"
        body: "Автоматический билд плагина из ветки ${{ github.ref_name }}. Хеш коммита: ${{ github.sha }}"
        draft: false
        prerelease: false
        files: target/*.jar # Указываем путь к скомпилированному плагину
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Этот токен Гитхаб создает сам, ничего настраивать не нужно
