name: Build and Release Purpur Plugin

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    # НОВЫЙ ШАГ: Создаем папку и скачиваем ядро напрямую по ссылке
    - name: Download Purpur Core
      run: |
        mkdir -id libs
        wget -O libs/purpur-26.1.2.jar https://repo.purpurmc.org/snapshots/org/purpurmc/purpur/purpur/26.1.2-SNAPSHOT/purpur-26.1.2-2592.jar

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Create Release and Upload Jar
      uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_number }}
        name: "Авто-сборка #${{ github.run_number }}"
        body: "Автоматический билд плагина. Хеш коммита: ${{ github.sha }}"
        draft: false
        prerelease: false
        files: target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
